import {
    Home, User, Users, Settings, Bell, Folder, File, ClipboardList, List, Calendar, LogOut, Trash2, BarChart, HelpCircle, Activity, AlertCircle, Check, Edit, Plus, Save, Search, ArrowLeft, ArrowRight, Info, Menu, Minus, PlusCircle, PlusSquare, Upload, Download, Eye, EyeOff, Link, Lock, Mail, MapPin, Monitor, Moon, MoreHorizontal, MoreVertical, Power, Printer, RefreshCw, Share, ShoppingCart, Star, Sun, Tag, Target, Timer, Unlock, Video, Wifi, Zap,
    UserCog, Key, ShieldCheck, UserPlus, UserMinus, UserCheck, UserX, UserCircle, UserRound, UserSquare,
    HardDrive, Database, Wrench,
    Briefcase, Building2,
    Package, Tags, Laptop, Copyright, // Changed Trademark to Copyright
    AirVent, Airplay, AlarmClock, AlertOctagon, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight, AtSign, Award, Banknote, BarChart2, Battery, BatteryCharging, Bluetooth, Bold, Book, Bookmark, Box, Brush, Bug, Cake, Camera, Cast, CheckCircle, CheckSquare, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Chrome, Circle, Clipboard, Clock, Cloud, CloudDrizzle, CloudLightning, CloudOff, CloudRain, CloudSnow, Code, Codepen, Coffee, Columns, Command, Compass, Contact, Contrast, Copy, CreditCard, Crop, Crosshair, Disc, Divide, DivideCircle, DivideSquare, DollarSign, DownloadCloud, Dribbble, Droplet, Edit2, Edit3, ExternalLink, Facebook, FastForward, Feather, Film, Filter, Flag, Flame, Flashlight, FolderMinus, FolderPlus, Frown, Gift, GitBranch, GitCommit, GitMerge, GitPullRequest, Github, Gitlab, Globe, GraduationCap, Grid, Hash, Headphones, Heart, Hexagon, Image, Instagram, Italic, Layers, Layout, LifeBuoy, Link2, Linkedin, Loader2, Locate, Maximize, Maximize2, Meh, MessageCircle, MessageSquare, Mic, MicOff, Minimize, Minimize2, MousePointer, Move, Music, Navigation, Navigation2, Octagon, Paperclip, Pause, PauseCircle, PenTool, Percent, Phone, PhoneCall, PhoneForwarded, PhoneIncoming, PhoneMissed, PhoneOff, PhoneOutgoing, PieChart, Pin, Play, PlayCircle, Podcast, QrCode, Radio, Receipt, Redo, RefreshCcw, Repeat, Rewind, Rocket, RotateCcw, RotateCw, Rss, Scissors, Send, Server, Shuffle, Sidebar, Signal, SkipBack, SkipForward, Slack, Slash, Sliders, Smartphone, Smile, Snowflake, SortAsc, SortDesc, Speaker, StopCircle, Sunrise, Sunset, Tablet, Terminal, Thermometer, ThumbsDown, ThumbsUp, Ticket, ToggleLeft, ToggleRight, Triangle, TrendingDown, TrendingUp, Truck, Tv, Twitch, Twitter, Type, Underline, Undo, Usb, VideoOff, Voicemail, Volume1, Volume2, VolumeX, Wallet, Watch, Webcam, Wind, Youtube,
} from 'lucide-react';

// Common UI and general-purpose icons
const commonIcons = [
    { name: 'Home', icon: Home },
    { name: 'User', icon: User },
    { name: 'Users', icon: Users },
    { name: 'Settings', icon: Settings },
    { name: 'Bell', icon: Bell },
    { name: 'Folder', icon: Folder },
    { name: 'File', icon: File },
    { name: 'List', icon: List },
    { name: 'Calendar', icon: Calendar },
    { name: 'LogOut', icon: LogOut },
    { name: 'Trash2', icon: Trash2 },
    { name: 'BarChart', icon: BarChart },
    { name: 'HelpCircle', icon: HelpCircle },
    { name: 'Activity', icon: Activity },
    { name: 'AlertCircle', icon: AlertCircle },
    { name: 'Check', icon: Check },
    { name: 'Edit', icon: Edit },
    { name: 'Plus', icon: Plus },
    { name: 'Save', icon: Save },
    { name: 'Search', icon: Search },
    { name: 'ArrowLeft', icon: ArrowLeft },
    { name: 'ArrowRight', icon: ArrowRight },
    { name: 'Info', icon: Info },
    { name: 'Menu', icon: Menu },
    { name: 'Minus', icon: Minus },
    { name: 'PlusCircle', icon: PlusCircle },
    { name: 'PlusSquare', icon: PlusSquare },
    { name: 'Upload', icon: Upload },
    { name: 'Download', icon: Download },
    { name: 'Eye', icon: Eye },
    { name: 'EyeOff', icon: EyeOff },
    { name: 'Link', icon: Link },
    { name: 'Lock', icon: Lock },
    { name: 'Mail', icon: Mail },
    { name: 'MapPin', icon: MapPin },
    { name: 'Monitor', icon: Monitor },
    { name: 'Moon', icon: Moon },
    { name: 'MoreHorizontal', icon: MoreHorizontal },
    { name: 'MoreVertical', icon: MoreVertical },
    { name: 'Power', icon: Power },
    { name: 'Printer', icon: Printer },
    { name: 'RefreshCw', icon: RefreshCw },
    { name: 'Share', icon: Share },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'Star', icon: Star },
    { name: 'Sun', icon: Sun },
    { name: 'Tag', icon: Tag },
    { name: 'Target', icon: Target },
    { name: 'Timer', icon: Timer },
    { name: 'Unlock', icon: Unlock },
    { name: 'Video', icon: Video },
    { name: 'Wifi', icon: Wifi },
    { name: 'Zap', icon: Zap },
];

// Icons related to user, role, and permission management
const accessIcons = [
    { name: 'UserCog', icon: UserCog },
    { name: 'Key', icon: Key },
    { name: 'ShieldCheck', icon: ShieldCheck },
    { name: 'UserPlus', icon: UserPlus },
    { name: 'UserMinus', icon: UserMinus },
    { name: 'UserCheck', icon: UserCheck },
    { name: 'UserX', icon: UserX },
    { name: 'UserCircle', icon: UserCircle },
    { name: 'UserRound', icon: UserRound },
    { name: 'UserSquare', icon: UserSquare },
];

// Icons for system-level features like backup, audit logs, and general utilities
const systemIcons = [
    { name: 'HardDrive', icon: HardDrive }, // Backup
    { name: 'Wrench', icon: Wrench }, // Utilities (changed from Tool)
    { name: 'Database', icon: Database },
    { name: 'ClipboardList', icon: ClipboardList }, // Audit Log
];

// Icons for employee and division management
const employeeIcons = [
    { name: 'Briefcase', icon: Briefcase },
    { name: 'Building2', icon: Building2 }, // Divisions
];

// Icons for asset management, categories, and brands
const assetIcons = [
    { name: 'Package', icon: Package }, // Assets
    { name: 'Tags', icon: Tags }, // Asset Categories
    { name: 'Laptop', icon: Laptop }, // Assets List
    { name: 'Copyright', icon: Copyright }, // Brands (changed from Trademark)
];

// Miscellaneous icons that don't fit into specific categories or are less frequently used
const miscellaneousIcons = [
    { name: 'AirVent', icon: AirVent },
    { name: 'Airplay', icon: Airplay },
    { name: 'AlarmClock', icon: AlarmClock },
    { name: 'AlertOctagon', icon: AlertOctagon },
    { name: 'AlertTriangle', icon: AlertTriangle },
    { name: 'AlignCenter', icon: AlignCenter },
    { name: 'AlignJustify', icon: AlignJustify },
    { name: 'AlignLeft', icon: AlignLeft },
    { name: 'AlignRight', icon: AlignRight },
    { name: 'AtSign', icon: AtSign },
    { name: 'Award', icon: Award },
    { name: 'Banknote', icon: Banknote },
    { name: 'BarChart2', icon: BarChart2 },
    { name: 'Battery', icon: Battery },
    { name: 'BatteryCharging', icon: BatteryCharging },
    { name: 'Bluetooth', icon: Bluetooth },
    { name: 'Bold', icon: Bold },
    { name: 'Book', icon: Book },
    { name: 'Bookmark', icon: Bookmark },
    { name: 'Box', icon: Box },
    { name: 'Brush', icon: Brush },
    { name: 'Bug', icon: Bug },
    { name: 'Cake', icon: Cake },
    { name: 'Camera', icon: Camera },
    { name: 'Cast', icon: Cast },
    { name: 'CheckCircle', icon: CheckCircle },
    { name: 'CheckSquare', icon: CheckSquare },
    { name: 'ChevronDown', icon: ChevronDown },
    { name: 'ChevronLeft', icon: ChevronLeft },
    { name: 'ChevronRight', icon: ChevronRight },
    { name: 'ChevronUp', icon: ChevronUp },
    { name: 'Chrome', icon: Chrome },
    { name: 'Circle', icon: Circle },
    { name: 'Clipboard', icon: Clipboard },
    { name: 'Clock', icon: Clock },
    { name: 'Cloud', icon: Cloud },
    { name: 'CloudDrizzle', icon: CloudDrizzle },
    { name: 'CloudLightning', icon: CloudLightning },
    { name: 'CloudOff', icon: CloudOff },
    { name: 'CloudRain', icon: CloudRain },
    { name: 'CloudSnow', icon: CloudSnow },
    { name: 'Code', icon: Code },
    { name: 'Codepen', icon: Codepen },
    { name: 'Coffee', icon: Coffee },
    { name: 'Columns', icon: Columns },
    { name: 'Command', icon: Command },
    { name: 'Compass', icon: Compass },
    { name: 'Contact', icon: Contact },
    { name: 'Contrast', icon: Contrast },
    { name: 'Copy', icon: Copy },
    { name: 'Copyright', icon: Copyright },
    { name: 'CreditCard', icon: CreditCard },
    { name: 'Crop', icon: Crop },
    { name: 'Crosshair', icon: Crosshair },
    { name: 'Disc', icon: Disc },
    { name: 'Divide', icon: Divide },
    { name: 'DivideCircle', icon: DivideCircle },
    { name: 'DivideSquare', icon: DivideSquare },
    { name: 'DollarSign', icon: DollarSign },
    { name: 'DownloadCloud', icon: DownloadCloud },
    { name: 'Dribbble', icon: Dribbble },
    { name: 'Droplet', icon: Droplet },
    { name: 'Edit2', icon: Edit2 },
    { name: 'Edit3', icon: Edit3 },
    { name: 'ExternalLink', icon: ExternalLink },
    { name: 'Facebook', icon: Facebook },
    { name: 'FastForward', icon: FastForward },
    { name: 'Feather', icon: Feather },
    { name: 'Film', icon: Film },
    { name: 'Filter', icon: Filter },
    { name: 'Flag', icon: Flag },
    { name: 'Flame', icon: Flame },
    { name: 'Flashlight', icon: Flashlight },
    { name: 'FolderMinus', icon: FolderMinus },
    { name: 'FolderPlus', icon: FolderPlus },
    { name: 'Frown', icon: Frown },
    { name: 'Gift', icon: Gift },
    { name: 'GitBranch', icon: GitBranch },
    { name: 'GitCommit', icon: GitCommit },
    { name: 'GitMerge', icon: GitMerge },
    { name: 'GitPullRequest', icon: GitPullRequest },
    { name: 'Github', icon: Github },
    { name: 'Gitlab', icon: Gitlab },
    { name: 'Globe', icon: Globe },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'Grid', icon: Grid },
    { name: 'Hash', icon: Hash },
    { name: 'Headphones', icon: Headphones },
    { name: 'Heart', icon: Heart },
    { name: 'Hexagon', icon: Hexagon },
    { name: 'Image', icon: Image },
    { name: 'Instagram', icon: Instagram },
    { name: 'Italic', icon: Italic },
    { name: 'Layers', icon: Layers },
    { name: 'Layout', icon: Layout },
    { name: 'LifeBuoy', icon: LifeBuoy },
    { name: 'Link2', icon: Link2 },
    { name: 'Linkedin', icon: Linkedin },
    { name: 'Loader2', icon: Loader2 },
    { name: 'Locate', icon: Locate },
    { name: 'Maximize', icon: Maximize },
    { name: 'Maximize2', icon: Maximize2 },
    { name: 'Meh', icon: Meh },
    { name: 'MessageCircle', icon: MessageCircle },
    { name: 'MessageSquare', icon: MessageSquare },
    { name: 'Mic', icon: Mic },
    { name: 'MicOff', icon: MicOff },
    { name: 'Minimize', icon: Minimize },
    { name: 'Minimize2', icon: Minimize2 },
    { name: 'MousePointer', icon: MousePointer },
    { name: 'Move', icon: Move },
    { name: 'Music', icon: Music },
    { name: 'Navigation', icon: Navigation },
    { name: 'Navigation2', icon: Navigation2 },
    { name: 'Octagon', icon: Octagon },
    { name: 'Paperclip', icon: Paperclip },
    { name: 'Pause', icon: Pause },
    { name: 'PauseCircle', icon: PauseCircle },
    { name: 'PenTool', icon: PenTool },
    { name: 'Percent', icon: Percent },
    { name: 'Phone', icon: Phone },
    { name: 'PhoneCall', icon: PhoneCall },
    { name: 'PhoneForwarded', icon: PhoneForwarded },
    { name: 'PhoneIncoming', icon: PhoneIncoming },
    { name: 'PhoneMissed', icon: PhoneMissed },
    { name: 'PhoneOff', icon: PhoneOff },
    { name: 'PhoneOutgoing', icon: PhoneOutgoing },
    { name: 'PieChart', icon: PieChart },
    { name: 'Pin', icon: Pin },
    { name: 'Play', icon: Play },
    { name: 'PlayCircle', icon: PlayCircle },
    { name: 'Podcast', icon: Podcast },
    { name: 'QrCode', icon: QrCode },
    { name: 'Radio', icon: Radio },
    { name: 'Receipt', icon: Receipt },
    { name: 'Redo', icon: Redo },
    { name: 'RefreshCcw', icon: RefreshCcw },
    { name: 'Repeat', icon: Repeat },
    { name: 'Rewind', icon: Rewind },
    { name: 'Rocket', icon: Rocket },
    { name: 'RotateCcw', icon: RotateCcw },
    { name: 'RotateCw', icon: RotateCw },
    { name: 'Rss', icon: Rss },
    { name: 'Scissors', icon: Scissors },
    { name: 'Send', icon: Send },
    { name: 'Server', icon: Server },
    { name: 'Shuffle', icon: Shuffle },
    { name: 'Sidebar', icon: Sidebar },
    { name: 'Signal', icon: Signal },
    { name: 'SkipBack', icon: SkipBack },
    { name: 'SkipForward', icon: SkipForward },
    { name: 'Slack', icon: Slack },
    { name: 'Slash', icon: Slash },
    { name: 'Sliders', icon: Sliders },
    { name: 'Smartphone', icon: Smartphone },
    { name: 'Smile', icon: Smile },
    { name: 'Snowflake', icon: Snowflake },
    { name: 'SortAsc', icon: SortAsc },
    { name: 'SortDesc', icon: SortDesc },
    { name: 'Speaker', icon: Speaker },
    { name: 'StopCircle', icon: StopCircle },
    { name: 'Sunrise', icon: Sunrise },
    { name: 'Sunset', icon: Sunset },
    { name: 'Tablet', icon: Tablet },
    { name: 'Terminal', icon: Terminal },
    { name: 'Thermometer', icon: Thermometer },
    { name: 'ThumbsDown', icon: ThumbsDown },
    { name: 'ThumbsUp', icon: ThumbsUp },
    { name: 'Ticket', icon: Ticket },
    { name: 'ToggleLeft', icon: ToggleLeft },
    { name: 'ToggleRight', icon: ToggleRight },
    { name: 'Triangle', icon: Triangle },
    { name: 'TrendingDown', icon: TrendingDown },
    { name: 'TrendingUp', icon: TrendingUp },
    { name: 'Truck', icon: Truck },
    { name: 'Tv', icon: Tv },
    { name: 'Twitch', icon: Twitch },
    { name: 'Twitter', icon: Twitter },
    { name: 'Type', icon: Type },
    { name: 'Underline', icon: Underline },
    { name: 'Undo', icon: Undo },
    { name: 'Usb', icon: Usb },
    { name: 'VideoOff', icon: VideoOff },
    { name: 'Voicemail', icon: Voicemail },
    { name: 'Volume1', icon: Volume1 },
    { name: 'Volume2', icon: Volume2 },
    { name: 'VolumeX', icon: VolumeX },
    { name: 'Wallet', icon: Wallet },
    { name: 'Watch', icon: Watch },
    { name: 'Webcam', icon: Webcam },
    { name: 'Wind', icon: Wind },
    { name: 'Youtube', icon: Youtube },
];

// Combine all icon categories into a single array for export
export const icons = [
    ...commonIcons,
    ...accessIcons,
    ...systemIcons,
    ...employeeIcons,
    ...assetIcons,
    ...miscellaneousIcons,
];