import {
  MdBarChart,
  MdShowChart,
  MdAutoGraph,
  MdPieChart,
  MdHeadsetMic,
  MdSell,
  MdInventory2,
  MdWarningAmber,
  MdGroups,
  MdStorage,
  MdApartment,
  MdTrendingUp,
  MdTrendingDown,
  MdInsights,
  MdTimeline,
  MdCategory,
  MdTag,
  MdChecklist,
  MdAnalytics,
  MdDeviceHub,
} from 'react-icons/md';

// A curated set of Horizon UI (Material Design) icons exposed via react-icons
// Extend this list as needed. Names should match iconMapper input keys.
export const horizonIcons = [
  { name: 'BarChart', icon: MdBarChart },
  { name: 'LineChart', icon: MdShowChart },
  { name: 'Activity', icon: MdAutoGraph },
  { name: 'ActivitySquare', icon: MdAutoGraph },
  { name: 'PieChart', icon: MdPieChart },
  { name: 'Headphones', icon: MdHeadsetMic },
  { name: 'Tags', icon: MdSell },
  { name: 'Package', icon: MdInventory2 },
  { name: 'AlertTriangle', icon: MdWarningAmber },
  { name: 'Users', icon: MdGroups },
  { name: 'HardDrive', icon: MdStorage },
  { name: 'Building2', icon: MdApartment },
  { name: 'TrendingUp', icon: MdTrendingUp },
  { name: 'TrendingDown', icon: MdTrendingDown },
  { name: 'Insights', icon: MdInsights },
  { name: 'Timeline', icon: MdTimeline },
  { name: 'Category', icon: MdCategory },
  { name: 'Tag', icon: MdTag },
  { name: 'Checklist', icon: MdChecklist },
  { name: 'Analytics', icon: MdAnalytics },
  { name: 'DeviceHub', icon: MdDeviceHub },
];
